J7srcz5l CRUD functionality for Routes
atlp-rwanda/incredible-phantom-backend pull request #37
Opened 2020-12-14 22:49 UTC by KundwaBruno

### WHAT DOES THIS PR DO?
This PR adds **CRUD** operations to route `/route`
This PR adds **CRUD** operations to route `/busStop`
### DESCRIPTION OF TASK TO BE COMPLETED
The operator should be able to create,delete and update a route.
The operator should be able to view a paginated list of routes in the system.
The users should be able to view a route's details.
Appropriate error messages are displayed on unsuccessful attempts.
### HOW SHOULD THIS BE MANUALLY TESTED?
**Testing** `/api/route` 

- Make a `.env` file and fill it with information as provided in the `.ev_example` file.
- First get a token granted from POST signin request on route `/api/users/signin` which is token you will be using to make requests along with the header `Authorization : token` on all routes because all routes are protected to only administratos and operators and also a body with email and password credentials of a sample admin from the mocks folder.

**Testing using postman**

- Make a POST request to route `/api/route` along with data that involves keys of start , end and distance and their values to **create** a route
- Make a GET request to route `/api/route` to **read** all routes' details in the database
- Make a GET request to route `/api/route/{routeID}` where id is the unique id given to a specific route to get that specific route's details
- Make a PATCH request to route `/api/route/{routeID}`  along with data that involves keys of start , end and distance and their values to **update** the specific route with its unique ID
- Make a DELETE request to route `/api/route/{routeID}` to **delete** that route with the specific ID
- Make a POST on route `/api/route/{routeID}` along with body that contains a key of `busStopId` and its value to assign a bus stop with the id to the route.

**Testing** `/api/busStop`

**Testing using postman**

- Make a POST request to route `/api/busStop` along with data that involves keys of sector , cell and coordinates and their values to **create** a bus stop
- Make a GET request to route `/api/busStop` to **read** all bus stop's details in the database
- Make a GET request to route `/api/busStop/{busStopId}` where `{busStopId}` is the unique id given to a specific bus stop to get that specific bus stop's details
- Make a PATCH request to route `/api/busStop/{busStopId}`  along with data that involves keys of sector , cell and coordinates and their values to **update** the specific bus stop with its unique ID
- Make a DELETE request to route `/api/busStop/{busStopId}` to **delete** that busStop with the specific ID

### RELEVANT TRELLO CARD
ID : J7srcz5l

2020-12-16 08:33 UTC, mansurissa approved these changes
LGTM

2020-12-16 09:43 UTC, GuevaraMarius approved these changes

2020-12-16 17:57 UTC, SIBONIYO approved these changes

2020-12-16 20:02 UTC, 41hulk reviewed
Nice Job Bruno

2020-12-16 23:14 UTC, samuel776 approved these changes

2020-12-17 08:54 UTC, raymond42 commented on src/controllers/busStop.js
> +    const busStopId = req.params;
does really all the req.params equals to busStopId? check on this, we should get the busStopId from req.params not equalizing them

2020-12-17 08:55 UTC, raymond42 commented on src/controllers/busStop.js
> +    const busStopId = req.params;
same as here, you should destructure the busStopId from req.params not equalizing them

2020-12-17 08:55 UTC, raymond42 commented on src/controllers/busStop.js
> +    const busStopId = req.params;
same thing here

2020-12-17 09:00 UTC, raymond42 requested changes
good job. please attend to the comments and revert to me

2020-12-20 16:43 UTC, raymond42 approved these changes
LGTM

2020-12-20 16:48 UTC, merged