Ft update profile uq dcj25
atlp-rwanda/incredible-phantom-backend pull request #40
Opened 2020-12-17 07:26 UTC by 41hulk

2020-12-17 19:38 UTC, KundwaBruno approved these changes

2020-12-17 19:39 UTC, KundwaBruno reviewed
Well done!

2020-12-17 19:39 UTC, GuevaraMarius approved these changes

2020-12-17 19:56 UTC, raymond42 commented on src/controllers/usersController.js
> +        console.log(error);
could you remove this console.log()?

2020-12-17 20:59 UTC, raymond42 commented on src/controllers/usersController.js
> +      const updatedUser = User.update({...req.body},
let's have await before User

2020-12-17 21:03 UTC, raymond42 commented on src/controllers/usersController.js
> +};
can you add an empty line at the end? check if your eslint is working

2020-12-17 21:06 UTC, raymond42 commented on src/test/mocks/mockUsers.js
> +  "nationalId":"1392417023348424"
should the nationalId not be an integer?

2020-12-17 21:10 UTC, raymond42 commented on src/test/users.test.js
> +  it('should fiind Names not provided', async() => {
let's have a good description of the tests. For example on this one you can say, it should throw an error when the names are not provided

2020-12-17 21:15 UTC, raymond42 requested changes
please attend to the comments and revert

2020-12-18 04:34 UTC, mansurissa approved these changes
Great job man

2020-12-20 20:25 UTC, raymond42 approved these changes
Nice work

2020-12-20 20:25 UTC, merged