Ft enquire buses info o6m b umpm
atlp-rwanda/incredible-phantom-backend pull request #50
Opened 2020-12-24 05:51 UTC by Egide138

2021-01-06 07:51 UTC, raymond42 commented on package.json
> +}
can you add an empty line at the end the file please?

2021-01-06 07:52 UTC, raymond42 commented on src/controllers/busControllers.js
> +    }
same as here

2021-01-06 07:53 UTC, raymond42 commented on src/controllers/usersController.js
> +
remove these empty lines. let's have only empty line. you should follow eslint rules

2021-01-06 07:53 UTC, GuevaraMarius commented on documentation/swaggerDoc.js
> +  export default docrouter
Good work Egide, can you use prettier to format your files.

2021-01-06 07:54 UTC, GuevaraMarius commented on package.json
> +}
same here

2021-01-06 07:55 UTC, GuevaraMarius commented on src/controllers/busControllers.js
> +    }
same here

2021-01-06 07:55 UTC, GuevaraMarius approved these changes

2021-01-06 07:55 UTC, GuevaraMarius commented on src/helpers/socket.js
> +});
same here

2021-01-06 07:57 UTC, raymond42 commented on src/database/migrations/20201214195024-create-bus.js
> +      },
can we have the same attributes as the ones we have in the model please?

2021-01-06 08:04 UTC, raymond42 commented on src/database/seeders/20201222074608-demo-bus.js
> +       driver:'Issa',
remove the driver. we are no longer assigning the driver when creating the bus

2021-01-06 08:04 UTC, raymond42 commented on src/helpers/socket.js
> +});
new line please

2021-01-06 08:05 UTC, raymond42 requested changes
attend to the comments and get back to me

2021-01-06 08:57 UTC, 41hulk reviewed
Nice Job Egide, i think you can work on the required changes @GuevaraMarius and @raymond42 Requested. LGTM

2021-01-06 11:44 UTC, KundwaBruno commented on src/controllers/busControllers.js
> +    console.log(error)
Great work Egide!, You can remove this console log.

2021-01-06 11:44 UTC, KundwaBruno commented on src/controllers/busControllers.js
> +      console.log(error)
Same as here, Remove the console log

2021-01-06 11:44 UTC, KundwaBruno commented on src/helpers/socket.js
> +const socket = require("socket.io");
You can use ES6 syntaxes

2021-01-06 11:44 UTC, KundwaBruno commented on src/helpers/socket.js
> +        console.log(data);
Same as here, remove the console logs

2021-01-06 11:44 UTC, KundwaBruno commented on src/test/bus.test.js
> +    console.log(busID)
Same as here

2021-01-06 14:55 UTC, samuel776 approved these changes

2021-01-07 06:04 UTC, raymond42 commented on src/database/migrations/20201214195024-create-bus.js
> +        defaultValue:""
instead of having `defaultValue: ""` we can replace it with `allowNull: true`

2021-01-07 11:02 UTC, samuel776 approved these changes

2021-01-07 16:14 UTC, GuevaraMarius approved these changes

2021-01-11 07:25 UTC, raymond42 approved these changes
LGTM

2021-01-11 07:27 UTC, merged